/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.FileTime;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Marci
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    
    public static int golyohelye;
    public static boolean megtalaltaE = false;
  
    
    public gui() {
        initComponents();
        golyotelhelyez();
        ellenorzes();
      
     
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IttaPiros");

        jButton2.setText("Pohár");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pohár");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Pohár");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Visszajelzés: ");

        jCheckBox1.setText("Új golyó minden tippnél");

        jMenu1.setText("File");

        jMenuItem2.setText("Betöltés");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Mentés");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Játék");

        jMenuItem1.setText("Új játék");
        jMenuItem1.setActionCommand("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setText("3 pohár");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("4 pohár");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jButton2)
                                .addGap(59, 59, 59)
                                .addComponent(jButton3)
                                .addGap(63, 63, 63)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       showMessageDialog(null, "Ez a mód jelenleg nem elérhető!");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     ellenoriz(1);
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     ellenoriz(2);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

     ellenoriz(3);
   
    }//GEN-LAST:event_jButton6ActionPerformed

    public void ellenoriz(int eazon){
    
     if(eazon == golyohelye){
      jLabel1.setText("Visszajelzés: Megtaláltad a golyót!");
           golyotujrakever();
           megtalaltaE = true;
      }else{
       jLabel1.setText("Visszajelzés: Rossz tipp!");
       }
        golyotujrakever();
             
    }

    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        golyotelhelyez();
               jLabel1.setText("Visszajelzés: ");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      
        mentes();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        beolvasbetolt();
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    public void ellenorzes(){
            File f = new File("tipp.deb");
        if(f.exists()) { 
              this.setTitle("A golyó a "+ golyohelye + ". pohár alatt található.");
        }

    }
    public void mentes(){
      
        int golyo = golyohelye;
        boolean megtalalta = megtalaltaE;
        boolean ujgolyotkertE = jCheckBox1.isSelected();
        String info = golyo+","+megtalalta+","+ujgolyotkertE;
        
        Path path = Paths.get("config.txt");
        byte[] bytes = info.getBytes(StandardCharsets.UTF_8);
 
        try {
            Files.write(path, bytes);    
            showMessageDialog(null, "Sikeres mentés!");
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    
    }
    public void beolvasbetolt(){
    
     try {
            List<String> beolvas = Files.readAllLines(Paths.get("config.txt"));
             String sor = beolvas.get(0);
             String[] d = sor.split(",");
             FileTime fajlido = Files.getLastModifiedTime(Paths.get("config.txt"));
             DateFormat datumformatum = new SimpleDateFormat("yyyy/MM/dd - hh:mm:ss");
             
             int golyohelyE = Integer.parseInt(d[0]);
             boolean megtalalta = Boolean.parseBoolean(d[1]);
             boolean ujgolyotkertE = Boolean.parseBoolean(d[2]);
            
            golyohelye = golyohelyE;
            if(megtalalta){
                jLabel1.setText("Visszajelzés: Megtaláltad a golyót!");
            }else{
               jLabel1.setText("Visszajelzés: Rossz tipp!");
            }
            
            if(ujgolyotkertE){
                jCheckBox1.setSelected(true);
            }else{
            jCheckBox1.setSelected(false);
            }
                 ellenorzes();
                 showMessageDialog(null, "Sikeres betöltés! \nMentés dátuma: " + datumformatum.format(fajlido.toMillis()));
             
        } catch (IOException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
              showMessageDialog(null, "HIBA: Betöltés nem sikerült!");
        }
    

    }
    
    
    
    public void golyotelhelyez(){
    Random rnd = new Random();
     golyohelye = rnd.nextInt(3 - 1 + 1) + 1;
     megtalaltaE = false;
    }
    
     public void golyotujrakever(){
     
     if(jCheckBox1.isSelected()){
     
     golyotelhelyez();
     }
     }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton6;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
